import type { Machine, Shift, Operator, Alert } from "./types"

export const mockMachines: Machine[] = [
  {
    id: "1",
    name: "CNC-001",
    type: "CNC",
    status: "ATIVA",
    location: "Setor A - Linha 1",
    lastMaintenance: new Date("2024-01-15"),
    nextMaintenance: new Date("2024-02-15"),
    operatingHours: 2450,
    efficiency: 87,
    currentOperator: "João Silva",
    specifications: {
      power: "15kW",
      capacity: "500kg",
      model: "CNC-X500",
      manufacturer: "TechMaq",
    },
  },
  {
    id: "2",
    name: "TORNO-002",
    type: "TORNO",
    status: "ATIVA",
    location: "Setor B - Linha 2",
    lastMaintenance: new Date("2024-01-10"),
    nextMaintenance: new Date("2024-02-10"),
    operatingHours: 1890,
    efficiency: 92,
    currentOperator: "Maria Santos",
    specifications: {
      power: "12kW",
      capacity: "300kg",
      model: "TORNO-T300",
      manufacturer: "MetalTech",
    },
  },
  {
    id: "3",
    name: "FRESADORA-003",
    type: "FRESADORA",
    status: "MANUTENCAO",
    location: "Setor C - Linha 1",
    lastMaintenance: new Date("2024-01-20"),
    nextMaintenance: new Date("2024-02-20"),
    operatingHours: 3200,
    efficiency: 78,
    specifications: {
      power: "18kW",
      capacity: "800kg",
      model: "FRES-F800",
      manufacturer: "PrecisionTools",
    },
  },
]

export const mockShifts: Shift[] = [
  {
    id: "1",
    name: "Turno Manhã",
    startTime: "06:00",
    endTime: "14:00",
    type: "MANHA",
    isActive: true,
    operators: ["1", "2", "3"],
    machines: ["1", "2"],
    supervisor: "Carlos Oliveira",
    date: new Date(),
    production: {
      target: 100,
      actual: 87,
      efficiency: 87,
    },
  },
  {
    id: "2",
    name: "Turno Tarde",
    startTime: "14:00",
    endTime: "22:00",
    type: "TARDE",
    isActive: false,
    operators: ["4", "5"],
    machines: ["1", "3"],
    supervisor: "Ana Costa",
    date: new Date(),
    production: {
      target: 95,
      actual: 92,
      efficiency: 97,
    },
  },
  {
    id: "3",
    name: "Turno Noite",
    startTime: "22:00",
    endTime: "06:00",
    type: "NOITE",
    isActive: false,
    operators: ["6"],
    machines: ["2"],
    supervisor: "Roberto Lima",
    date: new Date(),
    production: {
      target: 80,
      actual: 75,
      efficiency: 94,
    },
  },
]

export const mockOperators: Operator[] = [
  {
    id: "1",
    name: "João Silva",
    email: "joao.silva@rmx.com",
    role: "OPERADOR",
    shift: "MANHA",
    skills: ["CNC", "Torno"],
    certifications: ["NR-12", "Operação CNC"],
    isActive: true,
    hireDate: new Date("2022-03-15"),
    machinePermissions: ["1", "2"],
  },
  {
    id: "2",
    name: "Maria Santos",
    email: "maria.santos@rmx.com",
    role: "OPERADOR",
    shift: "MANHA",
    skills: ["Torno", "Fresadora"],
    certifications: ["NR-12", "Metrologia"],
    isActive: true,
    hireDate: new Date("2021-08-20"),
    machinePermissions: ["2", "3"],
  },
  {
    id: "3",
    name: "Pedro Costa",
    email: "pedro.costa@rmx.com",
    role: "TECNICO",
    shift: "MANHA",
    skills: ["Manutenção", "Elétrica"],
    certifications: ["NR-10", "NR-12"],
    isActive: true,
    hireDate: new Date("2020-01-10"),
    machinePermissions: ["1", "2", "3"],
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    type: "MANUTENCAO",
    severity: "ALTA",
    message: "FRESADORA-003 precisa de manutenção preventiva",
    machineId: "3",
    timestamp: new Date(),
    isRead: false,
  },
  {
    id: "2",
    type: "PRODUCAO",
    severity: "MEDIA",
    message: "Meta de produção do turno da manhã abaixo do esperado",
    timestamp: new Date(Date.now() - 3600000),
    isRead: false,
  },
]
